sudo: required
language: node_js
services:
  - docker
node_js:
  - '7'
addons:
  ssh_known_hosts: 47.100.112.11:3999
cache:
  directories:
    - front/node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_111bdbda2220_key -iv $encrypted_111bdbda2220_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - cd front
  - npm set registry https://registry.npm.taobao.org
install: 
  - npm install chromedriver --chromedriver_cdnurl=http://cdn.npm.taobao.org/dist/chromedriver
  - npm install
script: 
  - npm run build
after_success:
  - cd ~
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker-compose build
  - docker-compose push web_front web_back
  - ssh unsad@47.100.112.11 -p 3999 "./docker_start.sh"

