version: '3'
services:
  nginx_proxy:
    image: nginx:1.15.2-alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    links:
      - web:nginxserver
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
  