version: '3'
services:
  nginx_proxy:
    image: nginx:1.15.2-alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  mongo_db:
    image: mongo:3.4
    restart: always
    volumes:
      - ~/data/db:/data/db
    command: ["mongod", "--port", "19999"]
    expose: 
      - "19999"
  redis:
    image: redis:3.2
    restart: always
    expose:
      - "6379"
  web_front:
    image: unsad/web_front
    build:
      context: ./front
      dockerfile: ./Dockerfile
    depends_on:
      - web_back 
    expose:
      - "8080"
  web_back:
    image: unsad/web_back
    build:
      context: ./server
      dockerfile: ./Dockerfile
    depends_on:
      - mongo_db
      - redis
    expose:
      - "3000"

  