version: '3'
services:
  nginx_proxy:
    image: nginx:1.15.2-alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 4000:80
    links:
      - web:nginxserver
  mongo_db:
    image: mongo:3.4
    restart: always
    volumes:
      - /data/db:/data/db
    ports:
      - 19999:27017
  redis:
    image: redis:3.2
    restart: always
    ports:
      - 6379:6379
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      depends_on:
        - mongo_db
        - nginx_proxy
        - redis
  